### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by PQCraft** [septag/rizz#20]
An AUR package would be helpful for installing through the package manager.
Here are some guides:
[https://wiki.archlinux.org/title/Creating_packages](https://wiki.archlinux.org/title/Creating_packages)
[https://gist.github.com/keilmillerjr/dbfd9d60b2cd5fb440274c0a67a7db18](https://gist.github.com/keilmillerjr/dbfd9d60b2cd5fb440274c0a67a7db18)
And here is my PKGBUILD for my package:
[https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=clibasic](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=clibasic)

**Comment by septag** [comment]
sorry, I'm not planning to support linux packages for now. although PRs are always welcomed :)

**Comment by PQCraft** [comment]
F
