### ISSUE TITLE
compute shader

### ISSUE THREAD

**Issue by raptoravis** [septag/rizz#5]
Hi, I really love the way of rizz and its provided functionalities, like gfx, jobs, reflection, etc.
however, the compute shader seems not supported yet?

is it possible to support the compute shader so that it would be much convenient to do some advanced rendering tests.

so brilliant!

**Comment by septag** [comment]
Good to hear that you like it and thank you for your encouragement.

Compute shader is definitely planned, currently, the graphics backend is based on sokol_gfx, which doesn't support compute-shaders, but I'm planning to first add d3d11 CS support and then slowly move on to other APIs.

Right now, there are some other things that I have to do besides this, iOS support, documentation and an actual game example, so there would be some delay for this feature.

Cheers,

**Comment by septag** [comment]
D3D11 compute-shader support continued on PR #7

**Comment by septag** [comment]
First compute-shader support added, currently only under Direct3D11.

here is some work that still remains:
- OpenGL 4.0 support
- OpenGL compute shader 
- Possible compute support for OpenGL-ES using extensions
- Metal compute shader
- More compute examples
