### ISSUE TITLE
Support Wren Language

### ISSUE THREAD

**Issue by clsource** [septag/rizz#9]
Hello, this seems like a nice project.
I am interested in using [Wren](http://wren.io) as a scripting language.

This language is successfully used in other projects such as

https://tic.computer/
https://domeengine.com/
and https://luxeengine.com/

I'm willing to do a PR with a plugin, but I would need some guidance on where to look for integration :)

Thanks 👍

**Comment by septag** [comment]
cool. I'll be helping you in case you need any help.
design document is on the way, along with a game sample

**Comment by clsource** [comment]
Ok, that would be awesome.
I'll wait a little so I have a clearer picture on how to make a plugin 👍 

thanks.

**Comment by septag** [comment]
http://glitterbombg.com/devblog/posts/rizz-basics/#plugins

**Comment by Manuzor** [comment]
> 
> 
> http://glitterbombg.com/devblog/posts/rizz-basics/#plugins

Should be http://glitterbombg.com/blog/posts/rizz-basics/#plugins right?

**Comment by septag** [comment]
yes. I changed the urls a while back. thank you
